#!/usr/bin/python3
import json
import urllib.request

urllib.request.urlretrieve(json.loads(urllib.request.urlopen("http://xkcd.com/info.0.json").read().decode('utf-8'))['img'],"/home/navya/.config/i3/xkcd.png")
